'use strict';
const WorkoutUI=(()=>{
 let catalog=[],records=[],legacy=[],editor=null,owner=null,busy=false;
 const $=id=>document.getElementById(id), localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
 const clone=x=>JSON.parse(JSON.stringify(x)), exercise=id=>catalog.find(e=>e.id===id), sessions=()=>records.filter(r=>r.kind==='session').sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);
 const empty=(kind,name)=>({schema:'fitfuel.workout.v1',kind,name,date:localDate(),minutes:0,notes:'',exercises:[],token:crypto.randomUUID()});
 function entry(id){let e=exercise(id),timed=e?.timed,weight=e?.equipment==='kettlebells'?15:0;return {exerciseId:id,min:timed?20:8,max:timed?40:12,weight,increment:e?.equipment==='dumbbell'?5:0,cap:e?.equipment==='dumbbell'?50:e?.equipment==='kettlebells'?15:0,rest:60,effort:'unknown',sets:Array.from({length:3},()=>({weight,reps:timed?20:8,done:false}))};}
 async function hydrate(){
  const uid=s.user?.id;if(!uid)throw Error('Please sign in.');
  if(owner!==uid){records=[];legacy=[];editor=null;owner=uid;}
  const [data,db]=await Promise.all([catalog.length?catalog:fetch('./exercises.json?v=1').then(r=>{if(!r.ok)throw Error('Exercise library could not load.');return r.json();}),req('workouts.php')]);
  if(s.user?.id!==uid)throw Error('Account changed. Please reopen Workouts.');catalog=data;records=db.records;legacy=db.legacy;s.workouts=[...records.filter(r=>r.kind==='session').map(r=>({workout_date:r.date,workout_name:r.name,duration_minutes:r.minutes})),...legacy].sort((a,b)=>b.workout_date.localeCompare(a.workout_date));
 }
 async function open(tab='library') {try{await hydrate();view(tab);}catch(e){if(s.authenticated)app.innerHTML=`<div class="card"><h2>Workouts</h2><p role="alert">${esc(e.message)}</p><button onclick="WorkoutUI.open()">Retry</button></div>`;}}
 function shell(tab){header();nav('workouts');app.innerHTML=`<div class="card"><h2>Your training</h2><p class="muted">Build your routine. Record every set. See what to aim for next time.</p><div class="row">${[['library','My workouts'],['exercises','Exercises'],['history','History'],['charts','Strength charts']].map(([key,label])=>`<button class="${tab===key?'':'secondary'}" onclick="WorkoutUI.view('${key}')">${label}</button>`).join('')}</div></div><div id="workoutContent"></div>`;}
 function leave(){if(editor&&!confirm('Leave without saving these workout changes?'))return false;editor=null;return true;}
 function view(tab='library'){if(!leave())return;shell(tab);if(tab==='library')library();if(tab==='exercises')browse();if(tab==='history')history();if(tab==='charts')charts();}
 const starterPlans=[['Full body A',['Goblet_Squat','Dumbbell_Bench_Press_with_Neutral_Grip','One-Arm_Dumbbell_Row','Butt_Lift_Bridge','Dead_Bug']],['Full body B',['Bodyweight_Squat','Dumbbell_Incline_Row','Incline_Push-Up','Glute_Kickback','Side_Bridge']],['Full body C',['Split_Squat_with_Dumbbells','One-Arm_Kettlebell_Floor_Press','One-Arm_Dumbbell_Row','Hammer_Curls','Plank']]];
 function library(){const templates=records.filter(r=>r.kind==='template'),drafts=records.filter(r=>r.kind==='draft');$('workoutContent').innerHTML=`<div class="card"><div class="row"><h2>My workouts</h2><button onclick="WorkoutUI.create()">＋ Create workout</button></div><p class="muted">Personal to your account. Dumbbell weight means each dumbbell; for one implement, enter its weight. Bodyweight exercises start at 0 lb.</p>${drafts.map(r=>`<div class="recipe"><b>${esc(r.name)}</b> <span class="badge">Saved in progress</span><p>${esc(r.date)}</p><button onclick="WorkoutUI.edit(${r.id})">Resume</button> <button class="secondary" onclick="WorkoutUI.remove(${r.id})">Delete</button></div>`).join('')}${templates.map(r=>`<div class="recipe"><h3>${esc(r.name)}</h3><p class="muted">${r.exercises.length} exercises • ${r.exercises.reduce((n,e)=>n+e.sets.length,0)} planned sets</p><button onclick="WorkoutUI.start(${r.id})">Start workout</button> <button class="secondary" onclick="WorkoutUI.edit(${r.id})">Personalize</button> <button class="secondary" onclick="WorkoutUI.remove(${r.id})">Delete</button></div>`).join('')||'<p>No saved routines yet. Create one or personalize a starter below.</p>'}</div><div class="card"><h2>Starter routines</h2><p class="muted">Dumbbell, kettlebell and bodyweight options. Review movements and choose comfortable starting loads before training. Swap any exercise that does not suit you.</p>${starterPlans.map(([name,ids],i)=>`<div class="recipe"><h3>${name}</h3><p class="muted">${ids.map(id=>esc(exercise(id)?.name||id)).join(' • ')}</p><button onclick="WorkoutUI.starter(${i})">Personalize routine</button></div>`).join('')}</div>`;}
 function create(){editor=empty('template','My workout');editor.exercises=[entry(catalog[0].id)];renderEditor();}
 function starter(i){editor=empty('template',starterPlans[i][0]);editor.exercises=starterPlans[i][1].map(entry);renderEditor();}
 function edit(id){editor=clone(records.find(r=>r.id===id));renderEditor();}
 function start(id){const t=records.find(r=>r.id===id);editor=clone(t);delete editor.id;editor.token=crypto.randomUUID();editor.kind='draft';editor.templateId=id;editor.date=localDate();editor.minutes=0;editor.notes='';editor.exercises.forEach(e=>{
  const last=sessions().filter(r=>r.date<=localDate()).flatMap(r=>r.exercises).find(x=>x.exerciseId===e.exerciseId&&WorkoutCore.completed(x).length);
  const target=WorkoutCore.suggest(e,last,exercise(e.exerciseId)?.timed);e.suggestion=target.reason;e.effort='unknown';e.sets=e.sets.map(()=>({weight:target.weight,reps:target.reps,done:false}));
 });renderEditor();}
 const options=id=>catalog.map(e=>`<option value="${esc(e.id)}" ${e.id===id?'selected':''}>${esc(e.name)}</option>`).join('');
 function field(label,key,value,type='number',attrs=''){return `<label>${label}<input type="${type}" value="${esc(value)}" ${attrs} onchange="WorkoutUI.top('${key}',this.value)"></label>`;}
 function renderEditor(){shell('library');const template=editor.kind==='template';$('workoutContent').innerHTML=`<form id="workoutEditor" onsubmit="event.preventDefault();WorkoutUI.save('${template?'template':'session'}')"><div class="card"><h2>${template?'Personalize workout':'Log your sets'}</h2><p class="muted">${template?'Choose exercises, rep ranges, sets and available weight increments.':'Check off only finished sets. Weight is per dumbbell / single implement. For unilateral exercises, log reps per side; mark done after both sides.'}</p>${field('Workout name','name',editor.name,'text','required maxlength="100"')}<div class="two">${field('Date','date',editor.date,'date','required')}${!template?field('Duration (minutes)','minutes',editor.minutes,'number','min="0" max="1440"'):''}</div><label>Notes<textarea maxlength="4000" onchange="WorkoutUI.top('notes',this.value)">${esc(editor.notes)}</textarea></label></div>${editor.exercises.map((e,i)=>editorExercise(e,i,template)).join('')}<div class="card"><label>Add exercise<select id="addExercise">${options('')}</select></label><button type="button" class="secondary" onclick="WorkoutUI.add()">＋ Add exercise</button></div><div class="card row"><button id="saveWorkoutButton" type="submit">${template?'Save routine':'Finish workout'}</button>${!template?'<button type="button" class="secondary" onclick="WorkoutUI.save(\'draft\')">Save for later</button>':''}<button type="button" class="secondary" onclick="WorkoutUI.cancel()">Cancel</button><p id="workoutError" role="alert"></p></div></form>`;}
 function editorExercise(e,i,template){const ex=exercise(e.exerciseId),unit=ex?.timed?'seconds':'reps';return `<section class="card"><div class="row"><button type="button" class="exercise-title" onclick="WorkoutUI.demo('${e.exerciseId}')">${i+1}. ${esc(ex?.name||e.exerciseId)} ▷</button><button type="button" class="secondary" onclick="WorkoutUI.move(${i},-1)" aria-label="Move exercise up">↑</button><button type="button" class="secondary" onclick="WorkoutUI.move(${i},1)" aria-label="Move exercise down">↓</button><button type="button" class="secondary" onclick="WorkoutUI.drop(${i})">Remove</button></div><label>Swap exercise<select onchange="WorkoutUI.swap(${i},this.value)">${options(e.exerciseId)}</select></label>${template?`<div class="grid">${[['min','Minimum '+unit],['max','Maximum '+unit],['weight','Starting weight (lb)'],['increment','Weight step (lb; 0 = fixed)'],['cap','Maximum available weight (lb)'],['rest','Rest (seconds)']].map(([k,l])=>`<label>${l}<input type="number" step="${['min','max','rest'].includes(k)?'1':'0.5'}" min="${['min','max'].includes(k)?1:0}" max="${['min','max','rest'].includes(k)?600:k==='increment'?100:2000}" required value="${e[k]}" onchange="WorkoutUI.target(${i},'${k}',this.value)"></label>`).join('')}</div><label>Sets<input type="number" min="1" max="12" required value="${e.sets.length}" onchange="WorkoutUI.count(${i},this.value)"></label>`:`<p class="notice">${esc(e.suggestion||'Record the sets you complete.')}</p><p class="muted">Range: ${e.min}–${e.max} ${unit} • Rest: ${e.rest}s</p><div class="set-grid set-head"><span>Set</span><span>Weight (lb)</span><span>${unit}</span><span>Done</span></div>${e.sets.map((set,j)=>`<div class="set-grid"><b>${j+1}</b><input aria-label="Exercise ${i+1} set ${j+1} weight" type="number" min="0" max="2000" step="0.5" required value="${set.weight}" onchange="WorkoutUI.set(${i},${j},'weight',this.value)"><input aria-label="Exercise ${i+1} set ${j+1} ${unit}" type="number" min="0" max="600" required value="${set.reps}" onchange="WorkoutUI.set(${i},${j},'reps',this.value)"><input aria-label="Exercise ${i+1} set ${j+1} completed" type="checkbox" ${set.done?'checked':''} onchange="WorkoutUI.set(${i},${j},'done',this.checked)"></div>`).join('')}<div class="row"><button type="button" class="secondary" onclick="WorkoutUI.count(${i},${e.sets.length+1})">＋ Set</button><button type="button" class="secondary" onclick="WorkoutUI.count(${i},${e.sets.length-1})">Remove last set</button></div><label>How did this exercise feel?<select onchange="WorkoutUI.target(${i},'effort',this.value)">${[['unknown','Not recorded'],['easy','Easy — more reps available'],['right','Challenging with good form'],['hard','Too hard / form broke down'],['pain','Pain or discomfort']].map(([v,l])=>`<option value="${v}" ${e.effort===v?'selected':''}>${l}</option>`).join('')}</select></label>`}</section>`;}
 function top(k,v){editor[k]=k==='minutes'?Number(v):v;}
 function target(i,k,v){editor.exercises[i][k]=k==='effort'?v:Number(v);}
 function set(i,j,k,v){editor.exercises[i].sets[j][k]=k==='done'?v:Number(v);}
 function count(i,n){n=Math.max(1,Math.min(12,Math.floor(Number(n)||1)));const e=editor.exercises[i];e.sets=Array.from({length:n},(_,j)=>e.sets[j]||{weight:e.weight,reps:e.min,done:false});renderEditor();}
 function swap(i,id){editor.exercises[i]=entry(id);renderEditor();}
 function add(){if(editor.exercises.length>=30)return;editor.exercises.push(entry($('addExercise').value));renderEditor();}
 function drop(i){if(editor.exercises.length===1)return alert('Keep at least one exercise.');editor.exercises.splice(i,1);renderEditor();}
 function move(i,d){let j=i+d;if(j<0||j>=editor.exercises.length)return;[editor.exercises[i],editor.exercises[j]]=[editor.exercises[j],editor.exercises[i]];renderEditor();}
 function cancel(){if(confirm('Discard unsaved changes?')){editor=null;view();}}
 async function save(kind){if(busy)return;const form=$('workoutEditor');if(!form.reportValidity())return;busy=true;$('saveWorkoutButton').disabled=true;try{
  const record=clone(editor);record.kind=kind;if(kind==='template')record.exercises.forEach(e=>{e.sets=e.sets.map(()=>({weight:e.weight,reps:e.min,done:false}));delete e.suggestion;});
  const result=await req('workouts.php',{method:'POST',body:JSON.stringify({action:'save',id:editor.id||0,record})});editor.id=result.id;editor.kind=kind;
  await hydrate();editor=null;view(kind==='session'?'history':'library');
 }catch(e){if($('workoutError'))$('workoutError').textContent=e.message;}finally{busy=false;if($('saveWorkoutButton'))$('saveWorkoutButton').disabled=false;}}
 async function remove(id){if(!confirm('Delete this saved workout?'))return;try{await req('workouts.php',{method:'POST',body:JSON.stringify({action:'delete',id})});await hydrate();view();}catch(e){alert(e.message);}}
 function browse(){const groups=[...new Set(catalog.flatMap(e=>e.primaryMuscles))].sort();$('workoutContent').innerHTML=`<div class="card"><h2>Exercise library</h2><p>${catalog.length} exercises with step-by-step photos and instructions. Tap an exercise to see the demonstration.</p><label>Search<input id="exerciseSearch" type="search" oninput="WorkoutUI.filter()" placeholder="Exercise or muscle"></label><div class="two"><label>Equipment<select id="exerciseEquipment" onchange="WorkoutUI.filter()"><option value="">All equipment</option>${[...new Set(catalog.map(e=>e.equipment))].map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Muscle<select id="exerciseMuscle" onchange="WorkoutUI.filter()"><option value="">All muscles</option>${groups.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><div id="exerciseResults" class="exercise-list"></div></div>`;filter();}
 function filter(){const q=$('exerciseSearch').value.toLowerCase(),equipment=$('exerciseEquipment').value,muscle=$('exerciseMuscle').value;$('exerciseResults').innerHTML=catalog.filter(e=>(e.name+' '+e.primaryMuscles.join(' ')).toLowerCase().includes(q)&&(!equipment||e.equipment===equipment)&&(!muscle||e.primaryMuscles.includes(muscle))).map(e=>`<button class="exercise-card secondary" onclick="WorkoutUI.demo('${e.id}')"><img loading="lazy" src="./assets/exercises/${esc(e.images[0])}" alt="${esc(e.name)}"><span><b>${esc(e.name)}</b><small>${esc(e.equipment)} • ${esc(e.primaryMuscles.join(', '))}</small><small>View demonstration ▷</small></span></button>`).join('')||'<p>No exercises match those filters.</p>';}
 function demo(id){const e=exercise(id);if(!e)return;const dlg=document.createElement('dialog');dlg.className='exercise-dialog';dlg.innerHTML=`<button class="secondary" style="float:right" autofocus>Close</button><h2>${esc(e.name)}</h2><p class="muted">${esc(e.equipment)} • ${esc(e.primaryMuscles.join(', '))}</p><div class="demo-photos">${e.images.map((p,i)=>`<figure><img src="./assets/exercises/${esc(p)}" alt="${esc(e.name)}: position ${i+1}"><figcaption>Position ${i+1}</figcaption></figure>`).join('')}</div><p class="muted">Step-by-step photo demonstration. Move with control; stop if the movement causes pain.</p><ol>${e.instructions.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><a href="https://github.com/yuhonas/free-exercise-db" target="_blank" rel="noopener">Exercise source: Free Exercise DB</a>`;dlg.querySelector('button').onclick=()=>dlg.close();dlg.addEventListener('close',()=>dlg.remove());document.body.append(dlg);dlg.showModal();}
 function history(){const logs=sessions();$('workoutContent').innerHTML=`<div class="card"><h2>Workout history</h2><p class="muted">Completed sets are used for charts and progression. Unfinished sets stay visible in the workout.</p>${logs.map(r=>`<details class="recipe"><summary><b>${esc(r.name)}</b> • ${esc(r.date)} • ${r.minutes} min • ${r.exercises.reduce((n,e)=>n+WorkoutCore.completed(e).length,0)} sets</summary><p>${esc(r.notes)}</p>${r.exercises.map(e=>`<div class="recipe"><button class="exercise-title" onclick="WorkoutUI.demo('${e.exerciseId}')">${esc(exercise(e.exerciseId)?.name||e.exerciseId)} ▷</button><p>${e.sets.map((v,i)=>`Set ${i+1}: ${v.weight} lb × ${v.reps} ${exercise(e.exerciseId)?.timed?'sec':'reps'}${v.done?' ✓':' (not completed)'}`).join('<br>')}</p><small>Effort: ${esc(e.effort)}</small></div>`).join('')}<button class="secondary" onclick="WorkoutUI.edit(${r.id})">Edit log</button> <button class="secondary" onclick="WorkoutUI.remove(${r.id})">Delete</button></details>`).join('')||'<p>No completed workouts yet. Start a routine and finish your first session.</p>'}</div>${legacy.length?`<div class="card"><h2>Earlier workout logs</h2>${legacy.map(r=>`<div class="recipe"><b>${esc(r.workout_name)}</b><p>${esc(r.workout_date)} • ${Number(r.duration_minutes)||0} min</p><p>${esc(r.notes)}</p></div>`).join('')}</div>`:''}`;}
 function plot(points,label,unit){if(!points.length)return `<p class="muted">No data yet for ${esc(label.toLowerCase())}.</p>`;const values=points.map(p=>p.value),low=Math.min(...values),high=Math.max(...values),span=high-low||1;
 const coords=points.map((p,i)=>[55+(points.length===1?240:i*470/(points.length-1)),155-(p.value-low)*115]);return `<h3>${esc(label)}</h3><svg class="strength-chart" viewBox="0 0 560 205" role="img" aria-label="${esc(label)} over ${points.length} records"><path d="M55 25V165H535" fill="none" stroke="#cbd5e1"/><text x="4" y="40">${high.toFixed(1)}</text><text x="4" y="157">${low.toFixed(1)}</text><polyline points="${coords.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#2563eb" stroke-width="3"/>${coords.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="4" fill="#2563eb"><title>${esc(points[i].date)}: ${points[i].value.toFixed(1)} ${esc(unit)}</title></circle>`).join('')}<text x="55" y="193">${esc(points[0].date)}</text><text x="455" y="193">${esc(points[points.length-1].date)}</text></svg><details><summary>View chart values (${esc(unit)})</summary><table class="workout-table"><thead><tr><th>Date</th><th>${esc(label)}</th></tr></thead><tbody>${points.map(p=>`<tr><td>${esc(p.date)}</td><td>${p.value.toFixed(1)} ${esc(unit)}</td></tr>`).join('')}</tbody></table></details>`;}
 function charts(){const ids=[...new Set(sessions().flatMap(r=>r.exercises.filter(e=>WorkoutCore.completed(e).length).map(e=>e.exerciseId)))];$('workoutContent').innerHTML=`<div class="card"><h2>Strength & progress</h2><p class="muted">Compare your completed sets for the same exercise. Weight is per implement. Training volume = logged weight × reps; it does not include body weight or double the load for paired dumbbells.</p><label>Exercise<select id="chartExercise" onchange="WorkoutUI.drawCharts()">${ids.map(id=>`<option value="${esc(id)}">${esc(exercise(id)?.name||id)}</option>`).join('')}</select></label><div id="strengthPlots"></div></div>`;drawCharts();}
 function drawCharts(){const id=$('chartExercise').value;if(!id){$('strengthPlots').innerHTML='<p>Complete a workout to see your strength charts. No sample data is included.</p>';return;}const timed=exercise(id)?.timed;const rows=sessions().slice().reverse().map(r=>({date:r.date,entries:r.exercises.filter(e=>e.exerciseId===id)})).filter(r=>r.entries.length).map(r=>({date:r.date,...WorkoutCore.metrics({sets:r.entries.flatMap(e=>e.sets)})})).filter(r=>r.sets);
 const latest=rows.at(-1);$('strengthPlots').innerHTML=`<div class="grid"><div class="stat">Sessions<b>${rows.length}</b></div><div class="stat">Heaviest recorded<b>${Math.max(...rows.map(r=>r.weight))} lb</b></div><div class="stat">Latest completed sets<b>${latest?.sets||0}</b></div></div>`+plot(rows.map(r=>({date:r.date,value:r.weight})),'Heaviest completed set','lb')+plot(rows.map(r=>({date:r.date,value:r.reps})),timed?'Total hold time':'Total repetitions',timed?'seconds':'reps')+(timed?'':plot(rows.map(r=>({date:r.date,value:r.volume})),'Training volume','lb × reps'));}
 function bodyChart(){const el=document.createElement('div');el.className='card';el.innerHTML=plot((s.progress||[]).filter(x=>Number(x.weight)>0).slice().reverse().map(x=>({date:x.log_date,value:Number(x.weight)})),'Body weight','lb');app.prepend(el);}
 return {leave,open,view,create,starter,edit,start,top,target,set,count,swap,add,drop,move,cancel,save,remove,filter,demo,drawCharts,bodyChart};
})();
