<?php
require_once 'session.php';$uid=require_login();$method=$_SERVER['REQUEST_METHOD'];
function inp(){ $x=json_decode(file_get_contents('php://input'),true);return is_array($x)?$x:[]; }
function recipeRow($c,$id){$st=$c->prepare("SELECT * FROM recipes WHERE id=? LIMIT 1");$st->bind_param("i",$id);$st->execute();$r=$st->get_result()->fetch_assoc();$st->close();return$r?:null;}
function recipesFor($c,$uid){$fid=family_id_for_user($c,$uid);if($fid){$st=$c->prepare("SELECT r.* FROM recipes r LEFT JOIN family_members fm ON fm.user_id=r.user_id AND fm.family_id=? WHERE r.user_id IS NULL OR fm.family_id=? ORDER BY r.recipe_name");$st->bind_param("ii",$fid,$fid);}else{$st=$c->prepare("SELECT * FROM recipes WHERE user_id IS NULL OR user_id=? ORDER BY recipe_name");$st->bind_param("i",$uid);}$st->execute();$a=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();foreach($a as&$r)$r['ingredients']=json_decode($r['ingredients']??'[]',true)?:preg_split('/\r\n|\r|\n/',$r['ingredients']??'',-1,PREG_SPLIT_NO_EMPTY);return$a;}
if($method==='GET'){
$action=$_GET['action']??'bootstrap';
if($action==='bootstrap'){
$u=current_user($conn,$uid);$st=$conn->prepare("SELECT * FROM user_profiles WHERE user_id=?");$st->bind_param("i",$uid);$st->execute();$profile=$st->get_result()->fetch_assoc()?:[];$st->close();$date=$_GET['date']??date('Y-m-d');
$st=$conn->prepare("SELECT id,meal_type,food_name,servings,calories,protein_g,carbs_g,fat_g,fiber_g,notes,recipe_id,barcode,brand,serving_size,serving_unit,source,created_at FROM food_logs WHERE user_id=? AND food_date=? ORDER BY id DESC");$st->bind_param("is",$uid,$date);$st->execute();$food=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();
$st=$conn->prepare("SELECT COALESCE(SUM(ounces),0) total FROM water_logs WHERE user_id=? AND log_date=?");$st->bind_param("is",$uid,$date);$st->execute();$water=(float)($st->get_result()->fetch_assoc()['total']??0);$st->close();
$st=$conn->prepare("SELECT log_date,weight,body_fat_percent,waist_inches,chest_inches,hips_inches,arm_inches,thigh_inches,notes FROM progress_logs WHERE user_id=? ORDER BY log_date DESC");$st->bind_param("i",$uid);$st->execute();$progress=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();
$st=$conn->prepare("SELECT workout_date,workout_name,duration_minutes,notes,completed FROM workout_logs WHERE user_id=? AND completed=1 ORDER BY workout_date DESC,id DESC LIMIT 50");$st->bind_param("i",$uid);$st->execute();$workouts=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();
$plans=[];$st=$conn->prepare("SELECT mp.plan_date,mp.recipe_id,r.recipe_name,r.ingredients,r.calories_per_serving,r.protein_per_serving,r.carbs_per_serving,r.fat_per_serving FROM meal_plans mp JOIN recipes r ON r.id=mp.recipe_id WHERE mp.user_id=? AND mp.plan_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 6 DAY) ORDER BY mp.plan_date,mp.meal_order");$st->bind_param("i",$uid);$st->execute();$rows=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();foreach($rows as$x){$x['ingredients']=json_decode($x['ingredients']??'[]',true)?:[];$plans[$x['plan_date']][]=$x;}
$fid=family_id_for_user($conn,$uid);$family=[];$fi=null;if($fid){$st=$conn->prepare("SELECT id,name,invite_code,created_by FROM families WHERE id=?");$st->bind_param("i",$fid);$st->execute();$fi=$st->get_result()->fetch_assoc();$st->close();$st=$conn->prepare("SELECT u.id,u.first_name,u.last_name,u.email,fm.member_role FROM family_members fm JOIN users u ON u.id=fm.user_id WHERE fm.family_id=? ORDER BY u.first_name");$st->bind_param("i",$fid);$st->execute();$family=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();}
json_response(['success'=>true,'user'=>$u,'profile'=>$profile,'date'=>$date,'food'=>$food,'water'=>$water,'progress'=>$progress,'workouts'=>$workouts,'plans'=>$plans,'recipes'=>recipesFor($conn,$uid),'family'=>$family,'family_info'=>$fi]);
}
if($action==='recipes')json_response(['success'=>true,'recipes'=>recipesFor($conn,$uid)]);
json_response(['success'=>false,'message'=>'Unknown action.'],400);
}
$in=inp();$action=$in['action']??'';
if($action==='food_add'){$meal=$in['meal_type']??'snack';$name=trim($in['food_name']??'');if($name==='')json_response(['success'=>false,'message'=>'Food name is required.'],400);$date=$in['food_date']??date('Y-m-d');$serv=(float)($in['servings']??1);$cal=(float)($in['calories']??0);$pro=(float)($in['protein_g']??0);$cb=(float)($in['carbs_g']??0);$fat=(float)($in['fat_g']??0);$fiber=(float)($in['fiber_g']??0);$notes=$in['notes']??null;$rid=isset($in['recipe_id'])?(int)$in['recipe_id']:null;$bc=$in['barcode']??null;$brand=$in['brand']??null;$ss=$in['serving_size']??null;$su=$in['serving_unit']??null;$source=$in['source']??'manual';$st=$conn->prepare("INSERT INTO food_logs(user_id,food_date,meal_type,food_name,servings,calories,protein_g,carbs_g,fat_g,fiber_g,notes,recipe_id,barcode,brand,serving_size,serving_unit,source) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$st->bind_param("isssddddddsisssss",$uid,$date,$meal,$name,$serv,$cal,$pro,$cb,$fat,$fiber,$notes,$rid,$bc,$brand,$ss,$su,$source);if(!$st->execute())json_response(['success'=>false,'message'=>'Unable to add food.'],500);$id=$conn->insert_id;$st->close();json_response(['success'=>true,'id'=>$id]);}
if($action==='food_delete'){$id=(int)($in['id']??0);$st=$conn->prepare("DELETE FROM food_logs WHERE id=? AND user_id=?");$st->bind_param("ii",$id,$uid);$st->execute();$st->close();json_response(['success'=>true]);}
if($action==='water_add'){$oz=(float)($in['ounces']??0);if($oz<=0)json_response(['success'=>false,'message'=>'Amount must be positive.'],400);$date=$in['log_date']??date('Y-m-d');$st=$conn->prepare("INSERT INTO water_logs(user_id,log_date,ounces) VALUES(?,?,?)");$st->bind_param("isd",$uid,$date,$oz);$st->execute();$st->close();json_response(['success'=>true]);}
if($action==='progress_add'){$date=$in['log_date']??date('Y-m-d');$w=$in['weight']??null;$bf=$in['body_fat_percent']??null;$wa=$in['waist_inches']??null;$ch=$in['chest_inches']??null;$hi=$in['hips_inches']??null;$ar=$in['arm_inches']??null;$th=$in['thigh_inches']??null;$notes=$in['notes']??null;$st=$conn->prepare("INSERT INTO progress_logs(user_id,log_date,weight,body_fat_percent,waist_inches,chest_inches,hips_inches,arm_inches,thigh_inches,notes) VALUES(?,?,?,?,?,?,?,?,?,?)");$st->bind_param("isddddddds",$uid,$date,$w,$bf,$wa,$ch,$hi,$ar,$th,$notes);$st->execute();$st->close();json_response(['success'=>true]);}
if($action==='workout_add'){$date=$in['workout_date']??date('Y-m-d');$name=trim($in['workout_name']??'Workout');$dur=(int)($in['duration_minutes']??0);$notes=$in['notes']??null;$done=(int)($in['completed']??1);$st=$conn->prepare("INSERT INTO workout_logs(user_id,workout_date,workout_name,duration_minutes,notes,completed) VALUES(?,?,?,?,?,?)");$st->bind_param("isissi",$uid,$date,$name,$dur,$notes,$done);$st->execute();$st->close();json_response(['success'=>true]);}
if($action==='plan_save'){$date=$in['plan_date']??'';$ids=is_array($in['recipe_ids']??null)?$in['recipe_ids']:[];$st=$conn->prepare("DELETE FROM meal_plans WHERE user_id=? AND plan_date=?");$st->bind_param("is",$uid,$date);$st->execute();$st->close();$order=0;$st=$conn->prepare("INSERT INTO meal_plans(user_id,plan_date,recipe_id,meal_order) VALUES(?,?,?,?)");foreach($ids as $rid){$rid=(int)$rid;if(!recipeRow($conn,$rid))continue;$order++;$st->bind_param("isii",$uid,$date,$rid,$order);$st->execute();}$st->close();json_response(['success'=>true]);}
if($action==='recipe_add'){$name=trim($in['recipe_name']??'');if($name==='')json_response(['success'=>false,'message'=>'Recipe name is required.'],400);$ingredients=json_encode(array_values(array_filter($in['ingredients']??[])),JSON_UNESCAPED_UNICODE);$desc=$in['description']??null;$url=$in['source_url']??null;$type=$in['source_type']??'manual';$inst=$in['instructions']??null;$serv=(float)($in['servings']??1);$prep=$in['prep_time_minutes']??null;$cook=$in['cook_time_minutes']??null;$cal=(float)($in['calories_per_serving']??0);$pro=(float)($in['protein_per_serving']??0);$cb=(float)($in['carbs_per_serving']??0);$fat=(float)($in['fat_per_serving']??0);$fiber=(float)($in['fiber_per_serving']??0);$fav=(int)($in['is_favorite']??0);$st=$conn->prepare("INSERT INTO recipes(user_id,recipe_name,description,source_url,source_type,ingredients,instructions,servings,prep_time_minutes,cook_time_minutes,calories_per_serving,protein_per_serving,carbs_per_serving,fat_per_serving,fiber_per_serving,is_favorite) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$st->bind_param("issssssdiidddddi",$uid,$name,$desc,$url,$type,$ingredients,$inst,$serv,$prep,$cook,$cal,$pro,$cb,$fat,$fiber,$fav);if(!$st->execute())json_response(['success'=>false,'message'=>'Unable to save recipe.'],500);$st->close();json_response(['success'=>true]);}
if($action==='recipe_delete'){$id=(int)($in['id']??0);$st=$conn->prepare("DELETE FROM recipes WHERE id=? AND user_id=?");$st->bind_param("ii",$id,$uid);$st->execute();$st->close();json_response(['success'=>true]);}
if($action==='join_family'){$code=strtoupper(trim($in['invite_code']??''));if($code==='')json_response(['success'=>false,'message'=>'Enter a family code.'],400);$st=$conn->prepare("SELECT id FROM families WHERE invite_code=? LIMIT 1");$st->bind_param("s",$code);$st->execute();$f=$st->get_result()->fetch_assoc();$st->close();if(!$f)json_response(['success'=>false,'message'=>'Family code not found.'],404);$fid=(int)$f['id'];$st=$conn->prepare("SELECT 1 FROM family_members WHERE family_id=? AND user_id=?");$st->bind_param("ii",$fid,$uid);$st->execute();$st->store_result();$has=$st->num_rows>0;$st->close();if(!$has){$role='member';$st=$conn->prepare("INSERT INTO family_members(family_id,user_id,member_role) VALUES(?,?,?)");$st->bind_param("iis",$fid,$uid,$role);$st->execute();$st->close();}json_response(['success'=>true,'message'=>'Joined family successfully.']);}
json_response(['success'=>false,'message'=>'Unknown action.'],400);
?>